#ifndef _LINUX_HELMET_H
#define _LINUX__HELMET_H

#define	HELMET_POLLING_IN_DRIVER

#define HELMET_CAM_GET_STATUS		0
#define HELMET_CAM_GET_VERSION		1
#define HELMET_CAM_SET_COMMAND		2

#endif /* _LINUX_HELMET_H */
