#ifndef _SMSC_H
#define _SMSC_H


#define SMSC_VENDORID_LOW		0x00
#define SMSC_FUNCTIONCTRL		0x04
#define SMSC_INTENRISING		0x0D
#define SMSC_INTENFALLING		0x10
#define SMSC_DEBUG			0x15
#define SMSC_CARKITCTRL			0x19
#define SMSC_POWERIO			0x39

#define SMSC_FUNCTIONCTRL_XCVRSEL_L	0x01
#define SMSC_FUNCTIONCTRL_XCVRSEL_H	0x02
#define SMSC_FUNCTIONCTRL_TERMSEL	0x04
#define SMSC_FUNCTIONCTRL_OPMODE_L	0x08
#define SMSC_FUNCTIONCTRL_OPMODE_H	0x10
#define SMSC_FUNCTIONCTRL_RESET		0x20
#define SMSC_FUNCTIONCTRL_SUSPENDM	0x40

#define SMSC_INTENRISING_HOSTDIS	0x01
#define SMSC_INTENRISING_VBUSVALID	0x02
#define SMSC_INTENRISING_SESSVALID	0x04
#define SMSC_INTENRISING_SESSEND	0x08
#define SMSC_INTENRISING_IDGND		0x10

#define SMSC_INTENFALLING_HOSTDIS	0x01
#define SMSC_INTENFALLING_VBUSVALID	0x02
#define SMSC_INTENFALLING_SESSVALID	0x04
#define SMSC_INTENFALLING_SESSEND	0x08
#define SMSC_INTENFALLING_IDGND		0x10

#define SMSC_DEBUG_LINESTATE0		0x01
#define SMSC_DEBUG_LINESTATE1		0x02

#define SMSC_CARKITCTRL_PWR		0x01
#define SMSC_CARKITCTRL_IDGND		0x02
#define SMSC_CARKITCTRL_TXDEN		0x04
#define SMSC_CARKITCTRL_RXDEN		0x08
#define SMSC_CARKITCTRL_SPKLEFTEN	0x10
#define SMSC_CARKITCTRL_SPKRIGHTEN	0x20
#define SMSC_CARKITCTRL_MICEN		0x40

#define SMSC_POWERIO_RESERVED		0x01
#define SMSC_POWERIO_SWAP		0x02
#define SMSC_POWERIO_PULLUPDP		0x10
#define SMSC_POWERIO_PULLUPDM		0x20

#endif
